# Configuration options that both costmaps follow

# Here we set either the footprint of the robot or the radius of the robot if it is circular
footprint: [[-0.2, -0.2], [-0.2, 0.2], [0.35, 0.2], [0.35, -0.2]] # Turtlebot's footprint

robot_radius: 0.20
footprint_padding: 0.01

# Defines the coordinate frame the costmap should reference for the base of the robot
robot_base_frame: base_footprint

transform_tolerance: 0.5

resolution: 0.05

# Set thresholds on obstacle information put into the costmap. 
obstacle_range: 3.9
raytrace_range: 4.0

#Layer definitions
static:
  map_topic: /map
  subscribe_to_updates: true

obstacles_layer:
  observation_sources: laser
  laser: {data_type: LaserScan, clearing: true, marking: true, topic: mobile_base/sensors/laser_scan}

inflation:
  inflation_radius: 1.75
  cost_scaling_factor: 2.58

      